apiVersion: v1
baseDomain: ankersen.dev
metadata:
  name: okd
#  name: ocp
compute:
- name: worker
  replicas: 0
  architecture: amd64
controlPlane:
  name: master
  replicas: 3
  architecture: amd64
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    - cidr: fd01::/48
      hostPrefix: 64
  machineNetwork:
    - cidr: 192.168.20.0/24
    - cidr: 2600:1702:4fc0:12ae::/64
  serviceNetwork:
    - 172.30.0.0/16
    - fd02::/112
  networkType: OVNKubernetes
platform:
  baremetal:
    apiVIPs:
    - 192.168.20.21
    - 2600:1702:4fc0:12ae::20:21
    ingressVIPs:
    - 192.168.20.20
    - 2600:1702:4fc0:12ae::20:20
# Platform section for sno
# platform:
#  none: {}
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
  - baremetal
  - Build
#  - CloudCredential
#  - CloudControllerManager
  - ImageRegistry
  - Storage
  - Console
  - CSISnapshot
#  - DeploymentConfig
  - Ingress
#  - Insights
  - MachineAPI
  - marketplace
  - NodeTuning
#  - openshift-samples
  - OperatorLifecycleManager
  - OperatorLifecycleManagerV1
# pullSecret for okd
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMBhmJu9ZWIYgj9FvwfJ4/ZcVqyuhSf6nWCuBiAzEZUq'
fips: false
